$schema: "http://json-schema.org/draft-04/schema#"
title: serviceConfig
description: |
  This config file contains the generic parameters for the services.
type: object
required:
    - services

properties:
    services:
        description: A list of usb-folders under 'services' that which contain the active services
        type: array
        items:
            description: The path to the service descriptor under the services folder
            type: string

